// Sample product data with realistic market prices for Indian market
const products = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and premium sound quality.",
    price: 12999,
    category: "Electronics",
    images: ["/diverse-people-listening-headphones.png"],
    rating: 4.8,
    reviews: 120,
    inStock: true,
    stockQuantity: 25,
    new: true,
    featured: true,
    bestSeller: true,
    colors: ["Black", "White", "Silver"],
    sizes: [],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with this advanced smart watch featuring heart rate monitoring and GPS.",
    price: 8999,
    category: "Electronics",
    images: ["/modern-smartwatch.png"],
    rating: 4.5,
    reviews: 85,
    inStock: true,
    stockQuantity: 18,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black", "Blue", "Pink"],
    sizes: [],
  },
  {
    id: "3",
    name: "Casual Cotton T-Shirt",
    description: "Comfortable cotton t-shirt perfect for everyday wear.",
    price: 799,
    category: "Clothing",
    images: ["/plain-white-tshirt.png"],
    rating: 4.3,
    reviews: 210,
    inStock: true,
    stockQuantity: 50,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["White", "Black", "Gray", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "4",
    name: "Ergonomic Office Chair",
    description: "Comfortable ergonomic chair designed for long hours of sitting.",
    price: 9999,
    category: "Home Goods",
    images: ["/comfortable-armchair.png"],
    rating: 4.7,
    reviews: 68,
    inStock: true,
    stockQuantity: 12,
    new: false,
    featured: true,
    bestSeller: false,
    colors: ["Black", "Gray"],
    sizes: [],
  },
  {
    id: "5",
    name: "Bestselling Novel",
    description: "The latest bestselling fiction novel that everyone is talking about.",
    price: 399,
    category: "Books",
    images: ["/open-book-library.png"],
    rating: 4.9,
    reviews: 320,
    inStock: true,
    stockQuantity: 35,
    new: true,
    featured: false,
    bestSeller: true,
    colors: [],
    sizes: [],
  },
  {
    id: "6",
    name: "Professional DSLR Camera",
    description: "High-end DSLR camera for professional photography with advanced features.",
    price: 58999,
    category: "Electronics",
    images: ["/vintage-camera-still-life.png"],
    rating: 4.8,
    reviews: 45,
    inStock: true,
    stockQuantity: 8,
    new: false,
    featured: true,
    bestSeller: false,
    colors: ["Black"],
    sizes: [],
  },
  {
    id: "7",
    name: "Designer Handbag",
    description: "Luxury designer handbag made with premium materials.",
    price: 12999,
    category: "Accessories",
    images: ["/stylish-leather-handbag.png"],
    rating: 4.6,
    reviews: 72,
    inStock: true,
    stockQuantity: 15,
    new: true,
    featured: true,
    bestSeller: true,
    colors: ["Brown", "Black", "Tan"],
    sizes: [],
  },
  {
    id: "8",
    name: "Stainless Steel Water Bottle",
    description: "Eco-friendly insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 899,
    category: "Home Goods",
    images: ["/clear-water-bottle.png"],
    rating: 4.4,
    reviews: 180,
    inStock: true,
    stockQuantity: 40,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Silver", "Black", "Blue", "Red"],
    sizes: [],
  },
  {
    id: "9",
    name: "Wireless Bluetooth Earbuds",
    description: "True wireless earbuds with premium sound quality and long battery life.",
    price: 4999,
    category: "Electronics",
    images: ["/wireless-earbuds.png"],
    rating: 4.6,
    reviews: 95,
    inStock: true,
    stockQuantity: 30,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["Black", "White", "Blue"],
    sizes: [],
  },
  {
    id: "10",
    name: "Ultra HD Smart TV",
    description: "65-inch 4K Ultra HD Smart TV with built-in streaming apps and voice control.",
    price: 64999,
    category: "Electronics",
    images: ["/smart-tv-living-room.png"],
    rating: 4.7,
    reviews: 62,
    inStock: true,
    stockQuantity: 10,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black"],
    sizes: [],
  },
  {
    id: "11",
    name: "Slim Fit Dress Shirt",
    description: "Professional dress shirt with a modern slim fit design.",
    price: 1499,
    category: "Clothing",
    images: ["/classic-dress-shirt.png"],
    rating: 4.4,
    reviews: 128,
    inStock: true,
    stockQuantity: 45,
    new: false,
    featured: false,
    bestSeller: false,
    colors: ["White", "Blue", "Black", "Pink"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "12",
    name: "Designer Jeans",
    description: "Premium denim jeans with a comfortable stretch fit.",
    price: 2999,
    category: "Clothing",
    images: ["/folded-denim-stack.png"],
    rating: 4.5,
    reviews: 156,
    inStock: true,
    stockQuantity: 38,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Blue", "Black", "Gray"],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "13",
    name: "Luxury Scented Candle",
    description: "Hand-poured scented candle with 50+ hours of burn time.",
    price: 1299,
    category: "Home Goods",
    images: ["/scented-candle.png"],
    rating: 4.8,
    reviews: 87,
    inStock: true,
    stockQuantity: 25,
    new: false,
    featured: false,
    bestSeller: false,
    colors: ["White", "Beige", "Gray"],
    sizes: [],
  },
  {
    id: "14",
    name: "Ceramic Dinner Set",
    description: "12-piece ceramic dinner set with elegant design for everyday use.",
    price: 3499,
    category: "Home Goods",
    images: ["/ceramic-dinner-set.png"],
    rating: 4.6,
    reviews: 42,
    inStock: true,
    stockQuantity: 15,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["White", "Blue", "Gray"],
    sizes: [],
  },
  {
    id: "15",
    name: "Classic Fiction Collection",
    description: "Set of 5 classic fiction novels in hardcover edition.",
    price: 1999,
    category: "Books",
    images: ["/placeholder.svg?key=x4hpg"],
    rating: 4.9,
    reviews: 76,
    inStock: true,
    stockQuantity: 20,
    new: false,
    featured: true,
    bestSeller: false,
    colors: [],
    sizes: [],
  },
  {
    id: "16",
    name: "Cookbook: World Cuisines",
    description: "Comprehensive cookbook featuring recipes from around the world.",
    price: 899,
    category: "Books",
    images: ["/vintage-cookbook.png"],
    rating: 4.7,
    reviews: 58,
    inStock: true,
    stockQuantity: 30,
    new: true,
    featured: false,
    bestSeller: true,
    colors: [],
    sizes: [],
  },
  {
    id: "17",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots and RFID protection.",
    price: 1499,
    category: "Accessories",
    images: ["/leather-wallet.png"],
    rating: 4.5,
    reviews: 112,
    inStock: true,
    stockQuantity: 35,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Brown", "Black"],
    sizes: [],
  },
  {
    id: "18",
    name: "Polarized Sunglasses",
    description: "UV-protected polarized sunglasses with durable frame.",
    price: 2499,
    category: "Accessories",
    images: ["/stylish-sunglasses.png"],
    rating: 4.6,
    reviews: 89,
    inStock: true,
    stockQuantity: 22,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black", "Brown", "Blue"],
    sizes: [],
  },
  {
    id: "19",
    name: "Mechanical Keyboard",
    description: "RGB mechanical gaming keyboard with customizable keys.",
    price: 5999,
    category: "Electronics",
    images: ["/mechanical-keyboard.png"],
    rating: 4.7,
    reviews: 134,
    inStock: true,
    stockQuantity: 18,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["Black", "White"],
    sizes: [],
  },
  {
    id: "20",
    name: "Wireless Gaming Mouse",
    description: "High-precision wireless gaming mouse with programmable buttons.",
    price: 2999,
    category: "Electronics",
    images: ["/gaming-mouse.png"],
    rating: 4.8,
    reviews: 97,
    inStock: true,
    stockQuantity: 25,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Black", "White", "RGB"],
    sizes: [],
  },
  {
    id: "21",
    name: "Winter Parka Jacket",
    description: "Insulated winter parka with water-resistant exterior and warm lining.",
    price: 4999,
    category: "Clothing",
    images: ["/winter-parka.png"],
    rating: 4.7,
    reviews: 78,
    inStock: true,
    stockQuantity: 20,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black", "Navy", "Green"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "22",
    name: "Running Shoes",
    description: "Lightweight running shoes with responsive cushioning and breathable mesh.",
    price: 3499,
    category: "Clothing",
    images: ["/running-shoes-on-track.png"],
    rating: 4.6,
    reviews: 145,
    inStock: true,
    stockQuantity: 30,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Black/White", "Blue/Gray", "Red/Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
  },
  {
    id: "23",
    name: "Aromatherapy Diffuser",
    description: "Ultrasonic aromatherapy diffuser with LED mood lighting and auto shut-off.",
    price: 1999,
    category: "Home Goods",
    images: ["/placeholder.svg?key=z772b"],
    rating: 4.5,
    reviews: 92,
    inStock: true,
    stockQuantity: 25,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["White", "Wood Grain", "Black"],
    sizes: [],
  },
  {
    id: "24",
    name: "Throw Blanket",
    description: "Soft and cozy throw blanket perfect for your living room or bedroom.",
    price: 1299,
    category: "Home Goods",
    images: ["/cozy-throw-blanket.png"],
    rating: 4.8,
    reviews: 67,
    inStock: true,
    stockQuantity: 35,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Gray", "Beige", "Blue", "Green"],
    sizes: [],
  },
  {
    id: "25",
    name: "Self-Help Bestseller",
    description: "Internationally acclaimed self-help book to transform your mindset and habits.",
    price: 499,
    category: "Books",
    images: ["/self-help-book.png"],
    rating: 4.9,
    reviews: 215,
    inStock: true,
    stockQuantity: 40,
    new: true,
    featured: true,
    bestSeller: true,
    colors: [],
    sizes: [],
  },
  {
    id: "26",
    name: "Science Fiction Trilogy",
    description: "Award-winning science fiction trilogy box set in paperback.",
    price: 1299,
    category: "Books",
    images: ["/sci-fi-books.png"],
    rating: 4.7,
    reviews: 83,
    inStock: true,
    stockQuantity: 22,
    new: false,
    featured: false,
    bestSeller: false,
    colors: [],
    sizes: [],
  },
  {
    id: "27",
    name: "Statement Necklace",
    description: "Elegant statement necklace with crystal accents for special occasions.",
    price: 2499,
    category: "Accessories",
    images: ["/statement-necklace.png"],
    rating: 4.6,
    reviews: 54,
    inStock: true,
    stockQuantity: 15,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Silver", "Gold", "Rose Gold"],
    sizes: [],
  },
  {
    id: "28",
    name: "Leather Watch",
    description: "Classic analog watch with genuine leather strap and stainless steel case.",
    price: 3999,
    category: "Accessories",
    images: ["/leather-watch.png"],
    rating: 4.8,
    reviews: 76,
    inStock: true,
    stockQuantity: 20,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Brown", "Black", "Blue"],
    sizes: [],
  },
  // Mobile devices with realistic prices
  {
    id: "29",
    name: "Premium Smartphone X12",
    description: "Flagship smartphone with 6.7-inch AMOLED display, 108MP camera, and 5G connectivity.",
    price: 74999,
    category: "Mobile Devices",
    images: ["/premium-smartphone.png"],
    rating: 4.9,
    reviews: 342,
    inStock: true,
    stockQuantity: 25,
    new: true,
    featured: true,
    bestSeller: true,
    colors: ["Midnight Black", "Silver Frost", "Ocean Blue"],
    sizes: [],
    specs: {
      display: "6.7-inch AMOLED",
      processor: "Octa-core 3.0GHz",
      camera: "108MP main + 48MP ultra-wide + 12MP telephoto",
      battery: "5000mAh",
      storage: "256GB",
      ram: "12GB",
    },
  },
  {
    id: "30",
    name: "Budget Smartphone Y5",
    description: "Affordable smartphone with great performance, 6.5-inch display, and quad camera setup.",
    price: 14999,
    category: "Mobile Devices",
    images: ["/budget-smartphone.png"],
    rating: 4.5,
    reviews: 187,
    inStock: true,
    stockQuantity: 40,
    new: true,
    featured: false,
    bestSeller: true,
    colors: ["Black", "Green", "Blue"],
    sizes: [],
    specs: {
      display: "6.5-inch LCD",
      processor: "Octa-core 2.0GHz",
      camera: "48MP main + 8MP ultra-wide + 2MP macro + 2MP depth",
      battery: "4500mAh",
      storage: "128GB",
      ram: "6GB",
    },
  },
  {
    id: "31",
    name: "Pro Tablet 11",
    description: "High-performance tablet with 11-inch Retina display, powerful processor, and all-day battery life.",
    price: 49999,
    category: "Mobile Devices",
    images: ["/pro-tablet.png"],
    rating: 4.8,
    reviews: 156,
    inStock: true,
    stockQuantity: 20,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Space Gray", "Silver"],
    sizes: [],
    specs: {
      display: "11-inch Retina",
      processor: "M1 chip",
      camera: "12MP wide + 10MP ultra-wide",
      battery: "10 hours",
      storage: "256GB",
      ram: "8GB",
    },
  },
  {
    id: "32",
    name: "Budget Tablet 10.2",
    description: "Affordable tablet perfect for entertainment, browsing, and light productivity.",
    price: 24999,
    category: "Mobile Devices",
    images: ["/budget-tablet.png"],
    rating: 4.6,
    reviews: 203,
    inStock: true,
    stockQuantity: 30,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Silver", "Gold", "Space Gray"],
    sizes: [],
    specs: {
      display: "10.2-inch Retina",
      processor: "A13 Bionic",
      camera: "8MP back, 12MP front",
      battery: "10 hours",
      storage: "64GB",
      ram: "4GB",
    },
  },
  {
    id: "33",
    name: "Foldable Smartphone Z4",
    description: "Revolutionary foldable smartphone with dual screens and multitasking capabilities.",
    price: 124999,
    category: "Mobile Devices",
    images: ["/foldable-smartphone.png"],
    rating: 4.7,
    reviews: 98,
    inStock: true,
    stockQuantity: 15,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Phantom Black", "Phantom Silver"],
    sizes: [],
    specs: {
      display: "7.6-inch foldable AMOLED + 6.2-inch cover display",
      processor: "Snapdragon 8 Gen 1",
      camera: "50MP main + 12MP ultra-wide + 10MP telephoto",
      battery: "4400mAh",
      storage: "512GB",
      ram: "12GB",
    },
  },
  {
    id: "34",
    name: "Gaming Smartphone G1",
    description: "Smartphone designed for mobile gaming with high refresh rate display and advanced cooling system.",
    price: 44999,
    category: "Mobile Devices",
    images: ["/gaming-smartphone.png"],
    rating: 4.8,
    reviews: 124,
    inStock: true,
    stockQuantity: 22,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["Black", "Red"],
    sizes: [],
    specs: {
      display: "6.8-inch AMOLED, 144Hz",
      processor: "Snapdragon 8+ Gen 1",
      camera: "64MP main + 13MP ultra-wide",
      battery: "6000mAh",
      storage: "256GB",
      ram: "16GB",
    },
  },
  {
    id: "35",
    name: "E-Reader Tablet",
    description: "Lightweight e-reader with paper-like display and weeks of battery life.",
    price: 9999,
    category: "Mobile Devices",
    images: ["/e-reader-tablet.png"],
    rating: 4.9,
    reviews: 287,
    inStock: true,
    stockQuantity: 35,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Black", "White"],
    sizes: [],
    specs: {
      display: "7-inch e-ink, 300ppi",
      processor: "1GHz",
      camera: "None",
      battery: "6 weeks",
      storage: "32GB",
      ram: "1GB",
    },
  },
  {
    id: "36",
    name: "Kids Tablet",
    description: "Durable tablet designed for children with parental controls and educational content.",
    price: 7999,
    category: "Mobile Devices",
    images: ["/kids-tablet.png"],
    rating: 4.5,
    reviews: 176,
    inStock: true,
    stockQuantity: 28,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Blue", "Pink", "Green"],
    sizes: [],
    specs: {
      display: "8-inch HD",
      processor: "Quad-core 2.0GHz",
      camera: "2MP front and rear",
      battery: "12 hours",
      storage: "32GB",
      ram: "3GB",
    },
  },
  // Mobile accessories with realistic prices
  {
    id: "37",
    name: "Premium Smartphone Case",
    description: "Military-grade protection case with sleek design for premium smartphones.",
    price: 1499,
    category: "Mobile Accessories",
    images: ["/premium-phone-case.png"],
    rating: 4.7,
    reviews: 312,
    inStock: true,
    stockQuantity: 50,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Black", "Clear", "Navy Blue"],
    sizes: [],
    compatibility: ["Premium Smartphone X12", "Premium Smartphone X11"],
  },
  {
    id: "38",
    name: "Tablet Keyboard Case",
    description: "Protective case with integrated keyboard for enhanced productivity on tablets.",
    price: 5999,
    category: "Mobile Accessories",
    images: ["/tablet-keyboard-case.png"],
    rating: 4.6,
    reviews: 145,
    inStock: true,
    stockQuantity: 25,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black", "Gray"],
    sizes: [],
    compatibility: ["Pro Tablet 11", "Pro Tablet 12.9"],
  },
  {
    id: "39",
    name: "Fast Wireless Charger",
    description: "15W fast wireless charging pad compatible with all Qi-enabled devices.",
    price: 1999,
    category: "Mobile Accessories",
    images: ["/wireless-charger.png"],
    rating: 4.5,
    reviews: 267,
    inStock: true,
    stockQuantity: 40,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Black", "White"],
    sizes: [],
  },
  {
    id: "40",
    name: "Smartphone Camera Lens Kit",
    description: "Professional lens kit for smartphone photography including wide-angle, macro, and fisheye lenses.",
    price: 2999,
    category: "Mobile Accessories",
    images: ["/camera-lens-kit.png"],
    rating: 4.4,
    reviews: 183,
    inStock: true,
    stockQuantity: 30,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["Black"],
    sizes: [],
  },
  {
    id: "41",
    name: "Smartphone Gimbal Stabilizer",
    description: "3-axis gimbal stabilizer for smooth smartphone video recording.",
    price: 6999,
    category: "Mobile Accessories",
    images: ["/gimbal-stabilizer.png"],
    rating: 4.7,
    reviews: 156,
    inStock: true,
    stockQuantity: 20,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["Black", "White"],
    sizes: [],
  },
  {
    id: "42",
    name: "Rugged Tablet Case",
    description: "Heavy-duty protective case for tablets with built-in stand and shoulder strap.",
    price: 2499,
    category: "Mobile Accessories",
    images: ["/rugged-tablet-case.png"],
    rating: 4.8,
    reviews: 92,
    inStock: true,
    stockQuantity: 25,
    new: false,
    featured: false,
    bestSeller: false,
    colors: ["Black", "Orange"],
    sizes: [],
    compatibility: ["Pro Tablet 11", "Budget Tablet 10.2"],
  },
  {
    id: "43",
    name: "Smartphone Ring Holder",
    description: "360° rotating ring holder and stand for secure grip on smartphones.",
    price: 499,
    category: "Mobile Accessories",
    images: ["/ring-holder.png"],
    rating: 4.5,
    reviews: 378,
    inStock: true,
    stockQuantity: 60,
    new: false,
    featured: false,
    bestSeller: true,
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: [],
  },
  {
    id: "44",
    name: "Bluetooth Stylus Pen",
    description: "Precision stylus pen for tablets with palm rejection and pressure sensitivity.",
    price: 4999,
    category: "Mobile Accessories",
    images: ["/stylus-pen.png"],
    rating: 4.6,
    reviews: 214,
    inStock: true,
    stockQuantity: 30,
    new: true,
    featured: true,
    bestSeller: false,
    colors: ["White", "Black"],
    sizes: [],
    compatibility: ["Pro Tablet 11", "Pro Tablet 12.9"],
  },
  {
    id: "45",
    name: "Portable Power Bank 20000mAh",
    description: "High-capacity power bank with fast charging for smartphones and tablets.",
    price: 1999,
    category: "Mobile Accessories",
    images: ["/power-bank.png"],
    rating: 4.7,
    reviews: 423,
    inStock: true,
    stockQuantity: 45,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Black", "White"],
    sizes: [],
  },
  {
    id: "46",
    name: "Smartphone Privacy Screen Protector",
    description: "Tempered glass screen protector with privacy filter to prevent side viewing.",
    price: 999,
    category: "Mobile Accessories",
    images: ["/privacy-screen-protector.png"],
    rating: 4.4,
    reviews: 187,
    inStock: true,
    stockQuantity: 50,
    new: false,
    featured: false,
    bestSeller: false,
    colors: ["Black"],
    sizes: [],
    compatibility: ["Premium Smartphone X12", "Budget Smartphone Y5"],
  },
  {
    id: "47",
    name: "Foldable Bluetooth Keyboard",
    description: "Compact foldable keyboard for smartphones and tablets with multi-device connectivity.",
    price: 2999,
    category: "Mobile Accessories",
    images: ["/foldable-keyboard.png"],
    rating: 4.5,
    reviews: 156,
    inStock: true,
    stockQuantity: 25,
    new: true,
    featured: false,
    bestSeller: false,
    colors: ["Black", "White"],
    sizes: [],
  },
  {
    id: "48",
    name: "Smartphone Car Mount",
    description: "Adjustable car mount with wireless charging for smartphones.",
    price: 1499,
    category: "Mobile Accessories",
    images: ["/car-mount.png"],
    rating: 4.6,
    reviews: 278,
    inStock: true,
    stockQuantity: 35,
    new: false,
    featured: true,
    bestSeller: true,
    colors: ["Black"],
    sizes: [],
  },
]

// Get all products
export function getAllProducts() {
  return products
}

// Get product by ID
export function getProductById(id) {
  return products.find((product) => product.id === id)
}

// Get featured products
export function getFeaturedProducts() {
  return products.filter((product) => product.featured)
}

// Get best selling products
export function getBestSellingProducts(limit = 4) {
  return products.filter((product) => product.bestSeller).slice(0, limit)
}

// Get new products
export function getNewProducts() {
  return products.filter((product) => product.new)
}

// Get products by category
export function getProductsByCategory(category) {
  return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}

// Get related products (same category, excluding current product)
export function getRelatedProducts(product, limit = 4) {
  return products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit)
}

// Search products
export function searchProducts(query) {
  const searchTerm = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(searchTerm) ||
      product.description.toLowerCase().includes(searchTerm) ||
      product.category.toLowerCase().includes(searchTerm),
  )
}

// Get all categories
export function getAllCategories() {
  const categories = new Set()
  products.forEach((product) => {
    categories.add(product.category)
  })
  return Array.from(categories)
}
